name: hola-mundo
on: 
    - push
    - pull_request
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: echo-hello-world
              run: echo "hola mundo1"

    job2:
        runs-on: ubuntu-latest
        steps:
            - name: echo-hello-world
              run: echo "hola mundo2"

    job3:
        runs-on: ubuntu-latest
        steps:
            - name: echo-hello-world
              run: echo "hola mundo3"

 
